name: bddisk
description: A Baidu NetDisk Demo.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^2.12.5
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  filesize: ^1.0.4
  shared_preferences: ^0.5.7+2
  sqflite: ^1.3.0+1
  path_provider: ^1.6.8
  permission_handler: ^5.0.0+hotfix.6
  webview_flutter: ^0.3.22+1
  flutter_downloader:
    path: ../flutter_downloader
  dio: ^3.0.9
  workmanager: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
  assets:
    - assets/
